/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import Models.Invoice;
import Models.Sale;
import Services.AccountManager;
import Services.OrderManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barri
 */
public class history extends javax.swing.JFrame {
    ArrayList<Invoice> invoices  = OrderManager.getInvoiceAll();
    
    /**
     * Creates new form history
     */
    public history() {
        initComponents();
        DefaultTableModel tblModel = (DefaultTableModel) HistoryTbl.getModel();
        for(Invoice invoice : invoices) {
            int invoiceID = invoice.getInvoiceID();
            String invoiceDate = invoice.getInvoiceDate();
            int cashierID = invoice.getCashierID();
            double subTotal = invoice.getSubtotal();
            double totalAmount = invoice.getTotalAmount();
            
            Object[] addRow = {invoiceID, invoiceDate, cashierID, subTotal, totalAmount};
            
            tblModel.addRow(addRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        histroyTblPnl = new javax.swing.JScrollPane();
        HistoryTbl = new javax.swing.JTable();
        invoiceScrnPanel = new javax.swing.JScrollPane();
        invoiceTextArea = new javax.swing.JTextArea();
        historyOfTransactionPanel = new javax.swing.JPanel();
        historyOfTransactionLbl = new javax.swing.JLabel();
        historyOfTransactionLbl1 = new javax.swing.JLabel();
        historyOfTransactionLbl2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 220, 185));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HistoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Cashier ID", "SubTotal", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HistoryTbl.getTableHeader().setReorderingAllowed(false);
        HistoryTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryTblMouseClicked(evt);
            }
        });
        histroyTblPnl.setViewportView(HistoryTbl);
        if (HistoryTbl.getColumnModel().getColumnCount() > 0) {
            HistoryTbl.getColumnModel().getColumn(0).setResizable(false);
            HistoryTbl.getColumnModel().getColumn(1).setResizable(false);
            HistoryTbl.getColumnModel().getColumn(1).setPreferredWidth(150);
            HistoryTbl.getColumnModel().getColumn(2).setResizable(false);
            HistoryTbl.getColumnModel().getColumn(3).setResizable(false);
            HistoryTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(histroyTblPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 75, 458, 614));

        invoiceTextArea.setEditable(false);
        invoiceTextArea.setColumns(20);
        invoiceTextArea.setRows(5);
        invoiceScrnPanel.setViewportView(invoiceTextArea);

        jPanel1.add(invoiceScrnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 75, 497, 699));

        historyOfTransactionPanel.setBackground(new java.awt.Color(94, 54, 10));
        historyOfTransactionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        historyOfTransactionPanel.setForeground(new java.awt.Color(255, 255, 255));

        historyOfTransactionLbl.setBackground(new java.awt.Color(204, 0, 0));
        historyOfTransactionLbl.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        historyOfTransactionLbl.setForeground(new java.awt.Color(255, 255, 255));
        historyOfTransactionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyOfTransactionLbl.setText("History of Transaction");

        historyOfTransactionLbl1.setBackground(new java.awt.Color(204, 0, 0));
        historyOfTransactionLbl1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        historyOfTransactionLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/title.png"))); // NOI18N
        historyOfTransactionLbl1.setText("History of Transaction");

        historyOfTransactionLbl2.setBackground(new java.awt.Color(204, 0, 0));
        historyOfTransactionLbl2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        historyOfTransactionLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/title.png"))); // NOI18N
        historyOfTransactionLbl2.setText("History of Transaction");

        javax.swing.GroupLayout historyOfTransactionPanelLayout = new javax.swing.GroupLayout(historyOfTransactionPanel);
        historyOfTransactionPanel.setLayout(historyOfTransactionPanelLayout);
        historyOfTransactionPanelLayout.setHorizontalGroup(
            historyOfTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyOfTransactionPanelLayout.createSequentialGroup()
                .addComponent(historyOfTransactionLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(historyOfTransactionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(historyOfTransactionLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        historyOfTransactionPanelLayout.setVerticalGroup(
            historyOfTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyOfTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(historyOfTransactionLbl1)
                .addComponent(historyOfTransactionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(historyOfTransactionLbl2)
        );

        jPanel1.add(historyOfTransactionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 716, 174, 58));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) HistoryTbl.getModel();
        
        if(HistoryTbl.getSelectedRowCount() == 1) {
            int currentInvoiceID = Integer.parseInt(HistoryTbl.getValueAt(HistoryTbl.getSelectedRow(), 0).toString());
            tblModel.removeRow(HistoryTbl.getSelectedRow());
            OrderManager.deleteInvoice(currentInvoiceID);
            invoiceTextArea.setText("");
        } else {
            if(HistoryTbl.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "History of transaction is empty!");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a transaction to be removed!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    
    
    private void HistoryTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryTblMouseClicked
        // TODO add your handling code here:       
        if(HistoryTbl.getSelectedRowCount() == 1) {
        int currentInvoiceID = Integer.parseInt(HistoryTbl.getValueAt(HistoryTbl.getSelectedRow(), 0).toString());

        ArrayList<Sale> sales = OrderManager.getSales(currentInvoiceID);
        Invoice invoice = OrderManager.getInvoiceByID(currentInvoiceID);
        double subTotal = invoice.getSubtotal();
        double tax = 0.12 * subTotal;
        double total = invoice.getTotalAmount();

        String textTitle;
            textTitle = String.format("*********************************Taste The Coffee******************************\n"
                    + "Time\\Date: %s\tCashier: %s\n"
                    + "Invoice ID: %d\n"
                    + "**********************************************************************************\n"
                    + "Item Name:             \tQty\tPrice($)\tAmount\n"
                    , invoice.getInvoiceDate(), AccountManager.getUsernameByID(invoice.getCashierID()), invoice.getInvoiceID());

        String textItems = "";
        for(int i = 0; i < sales.size(); i++) {
            textItems += String.format("%d. %-20s\t%-3d\t%-8.2f\t%-6.2f\n"
                                      , i+1
                                      , sales.get(i).getProductName()
                                      , sales.get(i).getQuantity()
                                      , sales.get(i).getUnitPrice()
                                      , sales.get(i).getAmount());
        } 

        String textTotal = String.format("**********************************************************************************\n"
                                       + "Tax: %.2f\n"
                                       + "Sub Total: %.2f\n"
                                       + "Total: %.2f\n"
                                       + "**********************************************************************************\n"
                                       , tax, subTotal, total);
        
        invoiceTextArea.setText(textTitle + textItems + textTotal);
        } else {
            if(HistoryTbl.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "History of transaction is empty!");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a transaction to be removed!");
            }
        }
    }//GEN-LAST:event_HistoryTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HistoryTbl;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel historyOfTransactionLbl;
    private javax.swing.JLabel historyOfTransactionLbl1;
    private javax.swing.JLabel historyOfTransactionLbl2;
    private javax.swing.JPanel historyOfTransactionPanel;
    private javax.swing.JScrollPane histroyTblPnl;
    private javax.swing.JScrollPane invoiceScrnPanel;
    private javax.swing.JTextArea invoiceTextArea;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
